// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tender_Core_Logic.Data;

#nullable disable

namespace TenderCoreLogic.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250810204813_init-base-tables")]
    partial class initbasetables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BaseTenderTag", b =>
                {
                    b.Property<Guid>("TagsTagID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TendersTenderID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TagsTagID", "TendersTenderID");

                    b.HasIndex("TendersTenderID");

                    b.ToTable("BaseTenderTag");
                });

            modelBuilder.Entity("Tender_Core_Logic.Models.BaseTender", b =>
                {
                    b.Property<Guid>("TenderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ClosingDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateAppended")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PublishedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SupportingDocs")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TenderID");

                    b.ToTable("BaseTender", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Tender_Core_Logic.Models.Tag", b =>
                {
                    b.Property<Guid>("TagID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TagName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TagID");

                    b.ToTable("Tag");
                });

            modelBuilder.Entity("Tender_Core_Logic.Models.EskomTender", b =>
                {
                    b.HasBaseType("Tender_Core_Logic.Models.BaseTender");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Audience")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OfficeLocation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Province")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reference")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenderNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("EskomTender", (string)null);
                });

            modelBuilder.Entity("Tender_Core_Logic.Models.eTender", b =>
                {
                    b.HasBaseType("Tender_Core_Logic.Models.BaseTender");

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Currency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProcurementMethod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProcurementMethodDetails")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProcuringEntity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenderNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tenderer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Value")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.ToTable("eTender", (string)null);
                });

            modelBuilder.Entity("BaseTenderTag", b =>
                {
                    b.HasOne("Tender_Core_Logic.Models.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagsTagID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tender_Core_Logic.Models.BaseTender", null)
                        .WithMany()
                        .HasForeignKey("TendersTenderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tender_Core_Logic.Models.EskomTender", b =>
                {
                    b.HasOne("Tender_Core_Logic.Models.BaseTender", null)
                        .WithOne()
                        .HasForeignKey("Tender_Core_Logic.Models.EskomTender", "TenderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tender_Core_Logic.Models.eTender", b =>
                {
                    b.HasOne("Tender_Core_Logic.Models.BaseTender", null)
                        .WithOne()
                        .HasForeignKey("Tender_Core_Logic.Models.eTender", "TenderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
