// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tender_Core_Logic.Data;

#nullable disable

namespace TenderCoreLogic.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251025194539_etender-model-update")]
    partial class etendermodelupdate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StandardUser_Tag", b =>
                {
                    b.Property<Guid>("TagID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TagID", "UserID");

                    b.HasIndex("UserID");

                    b.ToTable("StandardUser_Tag");
                });

            modelBuilder.Entity("Tender_Core_Logic.Models.BaseTender", b =>
                {
                    b.Property<Guid>("TenderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AISummary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ClosingDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateAppended")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PublishedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TenderID");

                    b.ToTable("BaseTender", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Tender_Core_Logic.Models.SupportingDoc", b =>
                {
                    b.Property<Guid>("SupportingDocID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TenderID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("URL")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SupportingDocID");

                    b.HasIndex("TenderID");

                    b.ToTable("SupportingDocs");
                });

            modelBuilder.Entity("Tender_Core_Logic.Models.Tag", b =>
                {
                    b.Property<Guid>("TagID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TagName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TagID");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("Tender_Core_Logic.UserModels.TenderUser", b =>
                {
                    b.Property<Guid>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateAppended")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsSuperUser")
                        .HasColumnType("bit");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfilePicture")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserID");

                    b.ToTable("TenderUser", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Tender_Core_Logic.UserModels.User_Tender", b =>
                {
                    b.Property<Guid>("WatchlistID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FKTenderID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FKUserID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsNotified")
                        .HasColumnType("bit");

                    b.Property<bool>("IsWatched")
                        .HasColumnType("bit");

                    b.Property<string>("UserTenderStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("WatchlistID");

                    b.HasIndex("FKTenderID");

                    b.HasIndex("FKUserID");

                    b.HasIndex("FKTenderID", "FKUserID")
                        .IsUnique();

                    b.ToTable("User_Tender", (string)null);
                });

            modelBuilder.Entity("Tender_Tag", b =>
                {
                    b.Property<Guid>("TagID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TenderID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TagID", "TenderID");

                    b.HasIndex("TenderID");

                    b.ToTable("Tender_Tag");
                });

            modelBuilder.Entity("Tender_Core_Logic.Models.EskomTender", b =>
                {
                    b.HasBaseType("Tender_Core_Logic.Models.BaseTender");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Audience")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OfficeLocation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Province")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reference")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenderNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("EskomTender", (string)null);
                });

            modelBuilder.Entity("Tender_Core_Logic.Models.SanralTender", b =>
                {
                    b.HasBaseType("Tender_Core_Logic.Models.BaseTender");

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullTextNotice")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenderNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("SanralTender", (string)null);
                });

            modelBuilder.Entity("Tender_Core_Logic.Models.SarsTender", b =>
                {
                    b.HasBaseType("Tender_Core_Logic.Models.BaseTender");

                    b.Property<string>("BriefingSession")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenderNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("SarsTender", (string)null);
                });

            modelBuilder.Entity("Tender_Core_Logic.Models.TransnetTender", b =>
                {
                    b.HasBaseType("Tender_Core_Logic.Models.BaseTender");

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactPerson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Institution")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Region")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenderNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenderType")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("TransnetTender", (string)null);
                });

            modelBuilder.Entity("Tender_Core_Logic.Models.eTender", b =>
                {
                    b.HasBaseType("Tender_Core_Logic.Models.BaseTender");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Audience")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OfficeLocation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Province")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenderNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("eTender", (string)null);
                });

            modelBuilder.Entity("Tender_Core_Logic.UserModels.StandardUser", b =>
                {
                    b.HasBaseType("Tender_Core_Logic.UserModels.TenderUser");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("StandardUser", (string)null);
                });

            modelBuilder.Entity("Tender_Core_Logic.UserModels.SuperUser", b =>
                {
                    b.HasBaseType("Tender_Core_Logic.UserModels.TenderUser");

                    b.Property<string>("Organisation")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("SuperUser", (string)null);
                });

            modelBuilder.Entity("StandardUser_Tag", b =>
                {
                    b.HasOne("Tender_Core_Logic.Models.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tender_Core_Logic.UserModels.StandardUser", null)
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tender_Core_Logic.Models.SupportingDoc", b =>
                {
                    b.HasOne("Tender_Core_Logic.Models.BaseTender", "Tender")
                        .WithMany("SupportingDocs")
                        .HasForeignKey("TenderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tender");
                });

            modelBuilder.Entity("Tender_Core_Logic.UserModels.User_Tender", b =>
                {
                    b.HasOne("Tender_Core_Logic.Models.BaseTender", "FKTender")
                        .WithMany()
                        .HasForeignKey("FKTenderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tender_Core_Logic.UserModels.TenderUser", "FKUser")
                        .WithMany()
                        .HasForeignKey("FKUserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FKTender");

                    b.Navigation("FKUser");
                });

            modelBuilder.Entity("Tender_Tag", b =>
                {
                    b.HasOne("Tender_Core_Logic.Models.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tender_Core_Logic.Models.BaseTender", null)
                        .WithMany()
                        .HasForeignKey("TenderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tender_Core_Logic.Models.EskomTender", b =>
                {
                    b.HasOne("Tender_Core_Logic.Models.BaseTender", null)
                        .WithOne()
                        .HasForeignKey("Tender_Core_Logic.Models.EskomTender", "TenderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tender_Core_Logic.Models.SanralTender", b =>
                {
                    b.HasOne("Tender_Core_Logic.Models.BaseTender", null)
                        .WithOne()
                        .HasForeignKey("Tender_Core_Logic.Models.SanralTender", "TenderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tender_Core_Logic.Models.SarsTender", b =>
                {
                    b.HasOne("Tender_Core_Logic.Models.BaseTender", null)
                        .WithOne()
                        .HasForeignKey("Tender_Core_Logic.Models.SarsTender", "TenderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tender_Core_Logic.Models.TransnetTender", b =>
                {
                    b.HasOne("Tender_Core_Logic.Models.BaseTender", null)
                        .WithOne()
                        .HasForeignKey("Tender_Core_Logic.Models.TransnetTender", "TenderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tender_Core_Logic.Models.eTender", b =>
                {
                    b.HasOne("Tender_Core_Logic.Models.BaseTender", null)
                        .WithOne()
                        .HasForeignKey("Tender_Core_Logic.Models.eTender", "TenderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tender_Core_Logic.UserModels.StandardUser", b =>
                {
                    b.HasOne("Tender_Core_Logic.UserModels.TenderUser", null)
                        .WithOne()
                        .HasForeignKey("Tender_Core_Logic.UserModels.StandardUser", "UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tender_Core_Logic.UserModels.SuperUser", b =>
                {
                    b.HasOne("Tender_Core_Logic.UserModels.TenderUser", null)
                        .WithOne()
                        .HasForeignKey("Tender_Core_Logic.UserModels.SuperUser", "UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tender_Core_Logic.Models.BaseTender", b =>
                {
                    b.Navigation("SupportingDocs");
                });
#pragma warning restore 612, 618
        }
    }
}
